name: 'Netlify Actions'
description: 'Netlify deploy from GitHub Actions'
author: 'Ryo Ota'
inputs:
  publish-dir:
    description: Publish directory
    required: true
  deploy-message:
    description: Custom deploy message for Netlify
    required: false
  github-token:
    description: GitHub token
    required: false
  production-branch:
      description: Production branch
      required: false
  enable-pull-request-comment:
      description: Enable pull request comment
      required: false
  enable-commit-comment:
    description: Enable commit comment
    required: false
  overwrites-pull-request-comment:
    description: Overwrites pull request comment
    required: false
  netlify-config-path:
    description: Path to netlify.toml
    required: false
outputs:
  deploy-url:
    description: Deploy URL
runs:
  using: 'node12'
  main: 'dist/index.js'
